### PR TITLE
Fix bug where TargetPerson tag cannot be removed

### LINKED ISSUE #101: Tag remove does not work with TargetPerson

### PR DESCRIPTION
**Pull request by weiquany**
Fixes #101

### CODE REVIEW

**Review by kelvinou01 — APPROVED** [review]
LGTM, good job finding this bug.

File: src/main/java/seedu/address/logic/parser/FilterCommandParser.java [hunk 1]
```diff
@@ -59,8 +59,6 @@ public FilterCommand parse(String args) throws ParseException {
         }
         if (commandSpecifier.equals(FilterListCommand.COMMAND_SPECIFIER)
                 || commandSpecifier.equals(FilterListCommand.COMMAND_SPECIFIER_ALIAS)) {
-
-            System.out.println(commandSpecifier);
```
Comment (malwaregarry) [inline src/main/java/seedu/address/logic/parser/FilterCommandParser.java:63]: I forgot to remove this 😅

**Review by malwaregarry — COMMENTED** [review]
LGTM
